cmake_minimum_required(VERSION 3.16)
project(SnippyWebp C)
set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreaded)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
foreach(option ANIM_UTILS CWEBP DWEBP GIF2WEBP IMG2WEBP VWEBP WEBPINFO LIBWEBPMUX WEBPMUX EXTRAS WEBP_JS FUZZTEST)
  set(WEBP_BUILD_${option} OFF CACHE BOOL "" FORCE)
endforeach()
set(WEBP_USE_THREAD OFF CACHE BOOL "" FORCE)
add_subdirectory(${WEBP_SOURCE} upstream EXCLUDE_FROM_ALL)
add_library(snippywebp SHARED encoder.c)
target_include_directories(snippywebp PRIVATE ${WEBP_SOURCE}/src)
target_link_libraries(snippywebp PRIVATE webp)
target_compile_options(snippywebp PRIVATE /W4 /WX /guard:cf)
target_link_options(snippywebp PRIVATE /guard:cf /DYNAMICBASE /NXCOMPAT)
